### ISSUE TITLE
New pretest script fails on Windows

### ISSUE THREAD

**Issue by p-v-d-Veeken** [d3/d3-random#15]
Previous discussion: https://github.com/d3/d3-random/pull/13, https://github.com/d3/d3-random/issues/8

So the new pretest script still has some issues, it fails on windows with the error log attached below. I did some digging around and it seems that the `json2module` module tries to read and write from and to dev/stdin and dev/stdout respectively. The problem with this is that windows has no analogue for these device files. Related: http://superuser.com/questions/241272/windows-how-to-redirect-file-parameter-to-stdout-windows-equivalent-of-dev-s

	> d3-random@0.2.1 pretest ~\d3-random
	> rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js

	~\d3-random\node_modules\json2module\bin\json2module:21
	    if (error) throw error;
	               ^

	Error: ENOENT: no such file or directory, open 'C:\dev\stdout'
	    at Error (native)

	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
	npm ERR! node v5.0.0
	npm ERR! npm  v3.3.6
	npm ERR! code ELIFECYCLE
	npm ERR! d3-random@0.2.1 pretest: `rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the d3-random@0.2.1 pretest script 'rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js'.
	npm ERR! This is most likely a problem with the d3-random package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls d3-random
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\Users\Pepe\dropbox\workspace\d3-random\npm-debug.log

	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
	npm ERR! node v5.0.0
	npm ERR! npm  v3.3.6
	npm ERR! code ELIFECYCLE
	npm ERR! d3-random@0.2.1 prepublish: `npm run test && uglifyjs build/d3-random.js -c -m -o build/d3-random.min.js && rm -f build/d3-random.zip`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the d3-random@0.2.1 prepublish script 'npm run test && uglifyjs build/d3-random.js -c -m -o build/d3-random.min.js && rm -f build/d3-random.zip'.
	npm ERR! This is most likely a problem with the d3-random package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     npm run test && uglifyjs build/d3-random.js -c -m -o build/d3-random.min.js && rm -f build/d3-random.zip
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls d3-random
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     ~\d3-random\npm-debug.log

**Comment by mbostock** [comment]
Okay, I think the place to fix this is in [mbostock/rw](https://github.com/mbostock/rw). It should be possible to make rw.readFile and rw.writeFile use process.{stdin,stderr,stdout} under the hood, at least for the asynchronous methods.

**Comment by p-v-d-Veeken** [comment]
Sounds about right to me. I don't know much about filesystems, so I won't be much use there, but if you need help testing, I'd be happy to help. :)

**Comment by mbostock** [comment]
I’ve published [rw 1.3](https://github.com/mbostock/rw/releases/tag/v1.3.0) which maps /dev/stdin to process.stdin and /dev/stdout and /dev/stderr to process.stdout and process.stderr, respectively. That should fix this problem if you run npm update.

**Comment by mbostock** [comment]
Edit: Looks like npm update only updates the top-level dependencies, so you’ll have to do a reinstall, or I can bump json2module.

**Comment by mbostock** [comment]
Okay, I bumped json2module to 0.0.2. Please try again and let me know if it works?

**Comment by p-v-d-Veeken** [comment]
Nope, still fails with the same error as posted above. 

I've went into the node_modules folder to check if I was using the right version and I can verify that json2module 0.0.2 and rw 1.3 were installed.

**Comment by mbostock** [comment]
That doesn’t sound right. Can you please run this:

```
rm -rf node_modules
npm install
```

And then run

```
npm ls
```

And paste the output in here?

And of course, please try running `npm test` again to see if it works.

**Comment by p-v-d-Veeken** [comment]
Sure thing:

    d3-random@0.2.1 C:\Users\Pepe\dropbox\workspace\d3-random
    ├── d3-array@0.7.1
    ├─┬ faucet@0.0.1
    │ ├── defined@0.0.0
    │ ├── duplexer@0.1.1
    │ ├── minimist@0.0.5
    │ ├── sprintf@0.1.5
    │ ├─┬ tap-parser@0.4.3
    │ │ └─┬ readable-stream@1.1.13
    │ │   ├── core-util-is@1.0.2
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31
    │ ├─┬ tape@2.3.3
    │ │ ├── deep-equal@0.1.2
    │ │ └── jsonify@0.0.0
    │ └─┬ through2@0.2.3
    │   └─┬ xtend@2.1.2
    │     └── object-keys@0.4.0
    ├─┬ json2module@0.0.2
    │ └── rw@1.3.0
    ├─┬ rollup@0.25.4
    │ ├─┬ chalk@1.1.1
    │ │ ├─┬ ansi-styles@2.2.0
    │ │ │ └── color-convert@1.0.0
    │ │ ├── escape-string-regexp@1.0.5
    │ │ ├─┬ has-ansi@2.0.0
    │ │ │ └── ansi-regex@2.0.0
    │ │ ├── strip-ansi@3.0.1
    │ │ └── supports-color@2.0.0
    │ ├── minimist@1.2.0
    │ └─┬ source-map-support@0.3.3
    │   └─┬ source-map@0.1.32
    │     └── amdefine@1.0.0
    ├── seedrandom@2.4.2
    ├─┬ tape@4.5.1
    │ ├── deep-equal@1.0.1
    │ ├── defined@1.0.0
    │ ├── function-bind@1.1.0
    │ ├─┬ glob@7.0.3
    │ │ ├─┬ inflight@1.0.4
    │ │ │ └── wrappy@1.0.1
    │ │ ├─┬ minimatch@3.0.0
    │ │ │ └─┬ brace-expansion@1.1.3
    │ │ │   ├── balanced-match@0.3.0
    │ │ │   └── concat-map@0.0.1
    │ │ ├── once@1.3.3
    │ │ └── path-is-absolute@1.0.0
    │ ├── has@1.0.1
    │ ├── inherits@2.0.1
    │ ├── minimist@1.2.0
    │ ├── object-inspect@1.1.0
    │ ├── resolve@1.1.7
    │ ├── resumer@0.0.0
    │ ├─┬ string.prototype.trim@1.1.2
    │ │ ├─┬ define-properties@1.1.2
    │ │ │ ├── foreach@2.0.5
    │ │ │ └── object-keys@1.0.9
    │ │ └─┬ es-abstract@1.5.0
    │ │   ├─┬ es-to-primitive@1.1.1
    │ │   │ ├── is-date-object@1.0.1
    │ │   │ └── is-symbol@1.0.1
    │ │   ├── is-callable@1.1.3
    │ │   └── is-regex@1.0.3
    │ └── through@2.3.8
    └─┬ uglify-js@2.6.2
      ├── async@0.2.10
      ├── source-map@0.5.3
      ├── uglify-to-browserify@1.0.2
      └─┬ yargs@3.10.0
        ├── camelcase@1.2.1
        ├─┬ cliui@2.1.0
        │ ├─┬ center-align@0.1.3
        │ │ ├─┬ align-text@0.1.4
        │ │ │ ├─┬ kind-of@3.0.2
        │ │ │ │ └── is-buffer@1.1.3
        │ │ │ ├── longest@1.0.1
        │ │ │ └── repeat-string@1.5.4
        │ │ └── lazy-cache@1.0.3
        │ ├── right-align@0.1.3
        │ └── wordwrap@0.0.2
        ├── decamelize@1.2.0
        └── window-size@0.1.0

**Comment by mbostock** [comment]
The `npm ls` looks okay.

I have a guess as to what’s happening.

**Comment by mbostock** [comment]
Okay, please update to rw 1.3.2, and try again?

**Comment by mbostock** [comment]
(You’ll need to `rm -rf node_modules && npm install`, as `npm update` won’t do it, again.)

**Comment by p-v-d-Veeken** [comment]
Pretest and prepublish work now! However, my terminal now hangs indefinitely on the test script:

	$ rm -r -f node_modules && npm install

	> d3-random@0.2.1 prepublish ~\d3-random
	> npm run test && uglifyjs build/d3-random.js -c -m -o build/d3-random.min.js


	> d3-random@0.2.1 pretest ~\d3-random
	> rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js


	> d3-random@0.2.1 test ~\d3-random
	> faucet && eslint index.js src

**Comment by mbostock** [comment]
Does running faucet by itself hang?

```
node_modules/.bin/faucet
```

**Comment by p-v-d-Veeken** [comment]
Yup, it does hang.

**Comment by mbostock** [comment]
Hmm. We could try running [tape](https://github.com/substack/tape) directly instead of faucet. Does this work?

```
npm install tape
node_modules/.bin/tape test/**/*-test.js
```

**Comment by p-v-d-Veeken** [comment]
Affirmative!

	$ node_modules/.bin/tape test/**/*-test.js
	TAP version 13
	# randomBates(n) returns random numbers with a mean of one-half
	ok 1 should be in delta
	...
	(omitted)
	...
	ok 55 (unnamed assert)
	# randomUniform() [teardown]

	1..55
	# tests 55
	# pass  55

	# ok

**Comment by mbostock** [comment]
Okay, I’ll switch over to running tape directly. It makes the output ugly, but oh well.

**Comment by p-v-d-Veeken** [comment]
Seems like the best option yeah, I'll open an issue with faucet, see if they're willing to fix it.
